// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scanner.Infrastructure;

#nullable disable

namespace Scanner.Infrastructure.Migrations
{
    [DbContext(typeof(ScannerDbContext))]
    [Migration("20260915120701_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Scanner.CandidateProfile.CandidateProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Domains")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Seniority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Years")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CandidateProfiles");
                });

            modelBuilder.Entity("Scanner.CandidateProfile.ProfileTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Proficiency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechnologySlug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("ProfileTechnology");
                });

            modelBuilder.Entity("Scanner.JobScanning.Company", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Slug");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Scanner.JobScanning.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int>("Remoteness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seniority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Url")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Scanner.JobScanning.RoleTechnology", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechnologySlug")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId", "TechnologySlug");

                    b.ToTable("RoleTechnology");
                });

            modelBuilder.Entity("Scanner.JobScanning.ScrapeRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScrapeRuns");
                });

            modelBuilder.Entity("Scanner.JobScanning.ScrapeRunEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RolesFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolesNew")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScrapeRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeRunId");

                    b.ToTable("ScrapeRunEntry");
                });

            modelBuilder.Entity("Scanner.Matching.Match", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breakdown")
                        .HasColumnType("TEXT");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ScoredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScrapeRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId", "RoleId", "ScrapeRunId")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Scanner.SharedKernel.Technology", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.HasKey("Slug");

                    b.ToTable("Technologies");
                });

            modelBuilder.Entity("Scanner.SharedKernel.TechnologyAlias", b =>
                {
                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnologySlug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Alias");

                    b.HasIndex("TechnologySlug");

                    b.ToTable("TechnologyAlias");
                });

            modelBuilder.Entity("Scanner.CandidateProfile.CandidateProfile", b =>
                {
                    b.OwnsOne("Scanner.CandidateProfile.Preferences", "Preferences", b1 =>
                        {
                            b1.Property<int>("CandidateProfileId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Industries")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Locations")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PreferredTechnologies")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Remoteness")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("SeniorityFloor")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CandidateProfileId");

                            b1.ToTable("CandidateProfiles");

                            b1.WithOwner()
                                .HasForeignKey("CandidateProfileId");
                        });

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("Scanner.CandidateProfile.ProfileTechnology", b =>
                {
                    b.HasOne("Scanner.CandidateProfile.CandidateProfile", null)
                        .WithMany("Technologies")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scanner.JobScanning.Company", b =>
                {
                    b.OwnsMany("Scanner.JobScanning.Source", "Sources", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Ats")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CompanySlug")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("CompanySlug");

                            b1.ToTable("Source");

                            b1.WithOwner()
                                .HasForeignKey("CompanySlug");
                        });

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Scanner.JobScanning.RoleTechnology", b =>
                {
                    b.HasOne("Scanner.JobScanning.Role", null)
                        .WithMany("Technologies")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scanner.JobScanning.ScrapeRunEntry", b =>
                {
                    b.HasOne("Scanner.JobScanning.ScrapeRun", null)
                        .WithMany("Entries")
                        .HasForeignKey("ScrapeRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scanner.SharedKernel.TechnologyAlias", b =>
                {
                    b.HasOne("Scanner.SharedKernel.Technology", null)
                        .WithMany("Aliases")
                        .HasForeignKey("TechnologySlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scanner.CandidateProfile.CandidateProfile", b =>
                {
                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("Scanner.JobScanning.Role", b =>
                {
                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("Scanner.JobScanning.ScrapeRun", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Scanner.SharedKernel.Technology", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
